### ISSUE TITLE
[FEATURE]: Change review & giftcard

### ISSUE THREAD

**Issue by RukiyaTossou** [fdnd-agency/wogo#122]
We changed the layout if the reviews and the giftcard. The gift cars has the same style that  i used with the form; a lighter border around the content with a border radius so it gives a smooth  and soft look. 

This is how this section should look like. 

![Image](https://github.com/user-attachments/assets/3922e4d6-beb4-4d7a-b5a0-b5414c913e6c)

how it looks like currently:  

![Image](https://github.com/user-attachments/assets/bd625e12-6a12-44e1-947d-037065be8125)

-  Start with changing the review and then the gift card.

**Comment by RukiyaTossou** [comment]
Ik heb de positioneereing van het cadeautjes icon voor de mobile versie kunnen doen 
````css
.img-wrapper :global(img) {
    position: relative;
    top: 2.28rem;
    background-color: var(--page-bg-color);
  }

```

Alleen voor de desktop versie lukt het niet helemaal op de nette manier.  Ik gebruik nu  - waardes bij de top positie 

````css
.img-wrapper :global(img) {
      left: 12rem;
      position: relative;
      bottom: 16rem;
      top: -8rem;
    }
```

**Comment by zainablfz** [comment]
Je kan ook bij de media query voor desktop `top: unset` doen, dan heb je ook een lagere bottom waarde. Hoef je ook geen negatieve waardes te gebruiken :)

``` CSS

 @media (min-width: 48em) {
    h2 {
      max-width: 630px;
      font-size: var(--fs-lg);
    }
    .img-wrapper :global(img) {
      left: 12rem;
      position: relative;
      bottom: 7.5rem;
      top: unset;
    }
  }
```
